In [2]:
import numpy as np

In [7]:
marks = np.random.randint(1, 101, size=(3, 16, 10))

print("3D Marks Array:")
print(marks)
print("Shape :", marks.shape)

3D Marks Array:
[[[ 60  95  47   6  35  95   8  62  29  78]
  [ 59  39  33  86  52  41  76  60  18  97]
  [ 81  43  74  80  96  85   9  92  49  49]
  [ 29  78  93  21  89  55  74  94  47  34]
  [ 31  62  37  84  21  12  92  29  96  98]
  [ 51  62  92  22  45   8  22  60  23   1]
  [ 28  27  83  24  54  35   8  50  63  33]
  [ 82  73  39  99  75  20  37  60  56  77]
  [ 88  90  84  23  50  26  94  77  49  99]
  [ 68  53  78  29  15  93  17  71  61  17]
  [ 65  33  36  30  89  59  48  43  98  99]
  [ 61  53  87  85  53  98  29  57  45  45]
  [ 49  89  96  68  30  17   8   1   4  19]
  [ 24  46  16  45  37  53  86  46  40  55]
  [ 29  33  69  48  94  44  72  86  42   3]
  [ 73   3  97  40  99  43  80  59   2  76]]

 [[ 14  76  95  38  53   6  95  81  51  58]
  [ 79  77  63  81  81  60  76  88  74  14]
  [ 70  61  35  60  59  13  16  26  42  74]
  [ 71  19   8  99  64  16  40  72  92  45]
  [ 25  83   5  15  41  90  85   6  97  18]
  [ 66   2  49  82   3  44  63  19  94  12]
  [ 41  19  63

In [8]:
year_avg = np.mean(marks, axis=(1, 2))

print("Year-wise Average:")
for i in range(len(year_avg)):
    print("  Year", i+1, ":", round(year_avg[i], 2))

Year-wise Average:
  Year 1 : 53.97
  Year 2 : 53.45
  Year 3 : 50.97


In [9]:
student_total = np.sum(marks, axis=(0, 2))

print("Student-wise Total:")
for i in range(len(student_total)):
    print("  Student", i+1, ":", student_total[i])

Student-wise Total:
  Student 1 : 1527
  Student 2 : 1837
  Student 3 : 1563
  Student 4 : 1673
  Student 5 : 1529
  Student 6 : 1425
  Student 7 : 1640
  Student 8 : 1756
  Student 9 : 1590
  Student 10 : 1785
  Student 11 : 1739
  Student 12 : 1602
  Student 13 : 1129
  Student 14 : 1582
  Student 15 : 1458
  Student 16 : 1507


In [10]:
subject_high = np.max(marks, axis=(0, 1))

print("Subject-wise Highest Score:")
for i in range(len(subject_high)):
    print("  Subject", i+1, ":", subject_high[i])

Subject-wise Highest Score:
  Subject 1 : 95
  Subject 2 : 97
  Subject 3 : 97
  Subject 4 : 99
  Subject 5 : 99
  Subject 6 : 98
  Subject 7 : 100
  Subject 8 : 94
  Subject 9 : 100
  Subject 10 : 99


In [11]:
print("Marks below 40 before:", np.sum(marks < 40))

marks[marks < 40] = 40

print("Marks below 40 after :", np.sum(marks < 40))
print("Minimum mark now     :", np.min(marks))

Marks below 40 before: 168
Marks below 40 after : 0
Minimum mark now     : 40


In [14]:
sorted_marks = np.sort(marks, axis=2)
print("After  sorting -", sorted_marks)

After  sorting - [[[ 40  40  40  40  47  60  62  78  95  95]
  [ 40  40  40  41  52  59  60  76  86  97]
  [ 40  43  49  49  74  80  81  85  92  96]
  [ 40  40  40  47  55  74  78  89  93  94]
  [ 40  40  40  40  40  62  84  92  96  98]
  [ 40  40  40  40  40  45  51  60  62  92]
  [ 40  40  40  40  40  40  50  54  63  83]
  [ 40  40  40  56  60  73  75  77  82  99]
  [ 40  40  49  50  77  84  88  90  94  99]
  [ 40  40  40  40  53  61  68  71  78  93]
  [ 40  40  40  43  48  59  65  89  98  99]
  [ 40  45  45  53  53  57  61  85  87  98]
  [ 40  40  40  40  40  40  49  68  89  96]
  [ 40  40  40  40  45  46  46  53  55  86]
  [ 40  40  40  42  44  48  69  72  86  94]
  [ 40  40  40  43  59  73  76  80  97  99]]

 [[ 40  40  40  51  53  58  76  81  95  95]
  [ 40  60  63  74  76  77  79  81  81  88]
  [ 40  40  40  40  42  59  60  61  70  74]
  [ 40  40  40  40  45  64  71  72  92  99]
  [ 40  40  40  40  40  41  83  85  90  97]
  [ 40  40  40  40  44  49  63  66  82  94]
  [ 40  40  4